name: twitterx-bot

services:
  twitterx-bot:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: twitterx-bot
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - twitterx-bot-net


networks:
  twitterx-bot-net:
    name: twitterx-bot_shared_network
